### PR TITLE
add Torba.clean to remove Torba.home_path from cli

### PR DESCRIPTION
**Pull request by justindowning**
This PR adds a `clean` method to the CLI to remove the home_path.

### CODE REVIEW

**Comment by nashbridges** [comment]
What's the use case for this?

**Comment by justindowning** [comment]
For me, when I was testing initial implementation (especially with various `#import` files), I had to nuke this folder and `torba pack` to test my `Torbafile` and compiled assets. I don't have a production use case (yet?) as we haven't moved to it yet. Having a simple `clean` could prove useful for workflows that want to 'start fresh'.

**Comment by nashbridges** [comment]
Ah! I see.

I think what would be more useful for you is to have `list` command which prints out a content of packed assets + `install --dry` which doesn't touch `Torba.home_path` (installing into some temp path).
It would be even more convenient if `--dry` triggers `list` automatically.

What do you think? It seems like a more natural workflow.

**Comment by justindowning** [comment]
So, would `list` look like [`bundle show`](https://github.com/bundler/bundler/blob/a2d40cdde33186ab3bdd42c5080321ae89218a7b/lib/bundler/cli.rb#L202-L215) with name and tag/version? I like `install --dry` as a way to test completeness of a `Torbafile` (beyond syntax check of `verify`).

**Comment by nashbridges** [comment]
> So, would list look like bundle show with name and tag/version

It should also show package content, otherwise you couldn't check correctness of your `import` options.

**Comment by nashbridges** [comment]
I'm closing this in favour #16

**Pull request closed without merging**
