### PR TITLE
Add support for git repos

### PR DESCRIPTION
**Pull request by xfalcox**
Hey, as said on #35 git repos as packages sources would help some people.

Please review, and I will work to get this to an acceptable level!

Thanks for the Torba gem.

### CODE REVIEW

**Comment by nashbridges** [comment]
Current solution doesn't allow to specify commit/revision (or `ref` term that is used by Bundler). This means that two developers would potentially fetch different heads. This can quickly go out of control even within a team of local developers.

If we want to support revisions, then we can't shallow copy since you don't know the revision position beforehand.

[Acceptance test](https://github.com/torba-rb/torba/blob/master/test/acceptance-cli/pack_test.rb) is needed for a git repo. I see that you've chosen azer/left-pad. If you stick with it, I would fork it to the torba-rb organization, since the guy is unpredictable.

**Comment by xfalcox** [comment]
Hey, what about this:

```bash
git clone --depth 1 --branch {{tag or branch}} url
```

And we can call the option a **tag** and the user can fetch a specific tag. And we keep the fast shallow clones.

**Comment by nashbridges** [comment]
How much do you win with shallow copying in your projects?
I see that this option causes more trouble than gain https://github.com/junegunn/fzf/pull/114

**Comment by xfalcox** [comment]
Not that much actually.

Are you ok with:

```bash
git clone --branch {{tag or branch}} url
```

And a **tag** parameter on the Torbafile?

**Comment by nashbridges** [comment]
I think inevitably someone will request specifying a commit, but let's start with simple things and see how it goes.

**Pull request closed without merging**
