### PR TITLE
add complete example for capistrano 3 setup

### PR DESCRIPTION
**Pull request by justindowning**

### CODE REVIEW

**Comment by nashbridges** [comment]
Thanks for your contributions :)
Have you seen https://github.com/torba-rb/torba/pull/12 ?
It seems once merged where will be no need for this.

**Comment by nashbridges** [comment]
@justindowning, please review last changes in master and rebase/close this PR

**Comment by justindowning** [comment]
@nashbridges I rebased `master` and moved my example under the Capistrano heading. I like the full example here for newer users. Let me know what you think!

**Comment by nashbridges** [comment]
I think you've missed the point that since v0.5 `torba pack` is automatically run during `rake assets:precompile` which is definitely called somewhere else in your Capistrano script

**Comment by justindowning** [comment]
My apologies! I removed the superfluous `deploy:torba` cap task.

**Comment by nashbridges** [comment]
@mattbrictson since this will change your initial commit could you please have a look on it?

**Comment by mattbrictson** [comment]
Looks good! :+1:

**Comment by nashbridges** [comment]
https://github.com/torba-rb/torba/commit/429f6d99e10e3af6fd08544efc8a172c0c358914

@justindowning @mattbrictson Thank you guys!

**Pull request closed without merging**
