### PR TITLE
hotfix: Let curl retry 10 times if it fails

### PR DESCRIPTION
**Pull request by pcboy**
When using gh_release I found that github often gives me 502 bad gateway.
That makes torba fail. It would be great to retry so I suggest to add a --retry 10 to curl.

### CODE REVIEW

**Comment by nashbridges** [comment]
Wouldn't introducing retries create possible drawback of having very long installation process? I think we should have `max-timeout` in that case.

**Comment by pcboy** [comment]
Well, it's only gonna take longer when it fails. You want these retries anyway because otherwise your deployment is gonna fail. Maybe we can add a --retry-max-time if you want?

**Comment by nashbridges** [comment]
Yep, --retry-max-time would be much better.

**Comment by pcboy** [comment]
Well you need both though. By default curl is not retrying at all.
What about --retry 5 --retry-max-time 60? Are you ok with this?
Seems safe and the worse that can happen is one minute lost.

**Comment by nashbridges** [comment]
> Well you need both though. By default curl is not retrying at all.

Sure. My note was about `retry-max-time` vs `max-time`

> What about --retry 5 --retry-max-time 60?

Looks good

**Comment by pcboy** [comment]
Ok thank you!
I updated my commit with --retry 5 and --retry-max-time 60. =)

**Comment by nashbridges** [comment]
Merged into master.
Thanks for your contributions!

**Pull request closed without merging**
